### ISSUE TITLE
Usage of structural templates

### ISSUE THREAD

**Issue by s-kyungyong** [FreshAirTonight/af2complex#10]
Hi!

I am modelling a heterodimer complex with an available template structure. If the input proteins A and B have matches in the same template complex structure, would AF2complex use this information to infer the pose of A relative to B? Or is the individual chain of the template used only to model A and B separately, without considering their pose together? I felt that AF2-multimer functions like the latter, while I'd need the former... I wonder if this is what I would also see with AF2complex.

**Comment by FreshAirTonight** [comment]
AF2Complex consider templates individually as monomers like AF-Multimer. Thus, it cannot do what you want out of box. If the standard modeling protocol does not work for you, you may try to leave only the desired template for protein A and B in their monomer template set, respectively, and see if it works better.

Alternatively, you may force the consideration of a complex template by joining input features of A and B into a single feature set as for a single sequence but leave a long gap (>100AAs) between the two monomers. For the sequence features, you may join them in unpaired fashion; for the template features, use your desired complex template. Then, use two monomer DL models (model_1_ptm and model_2_ptm) to predict the complex structure as a monomer. This, however, is not straightforward and requires some manipulation of the input features.

**Comment by s-kyungyong** [comment]
Thank you for the suggestions :)! I will try those out!
