### ISSUE TITLE
Is it possible to use a known structure (in pdb format) for feature generation and interactions prediction

### ISSUE THREAD

**Issue by ZKrekhno** [FreshAirTonight/af2complex#12]
I am trying to model interactions with proteins for which the structures are already known (either crystal structures are solved or they have Alphafold predicted structures on Uniprot). Is there a way to just use these pdb files for interactions prediction rather than generating features from basic sequences?

**Comment by FreshAirTonight** [comment]
You may use PDB structures as templates as part of input features. But the prediction requires sequence input features as well.

**Comment by ZKrekhno** [comment]
Oh that sounds good. Thank you for the quick reply!
