### ISSUE TITLE
Error with run_fea_gen.sh

### ISSUE THREAD

**Issue by kimdn** [FreshAirTonight/af2complex#17]
I installed all requirements with
`pip install -r requirements.txt`
(also I installed AF2 already).

However, when I ran
`run_fea_gen.sh single_pair_of_RBD_NA.fasta`
I see
<img width="970" alt="Screen Shot 2023-04-08 at 9 22 21 PM" src="https://user-images.githubusercontent.com/3903446/230754786-97964727-3355-4e10-9062-68357301b627.png">

**Comment by FreshAirTonight** [comment]
Which AF2 version are you using? AF2Complex v1.4 works with AF v2.3.x environment after you add one additional python module networkx by `pip3 install networkx==2.5`. 

It seems that you have installed a higher version of jaxlib, try this:
`pip3 install jax==0.3.25 jaxlib==0.3.25+cuda11.cudnn805 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`

**Comment by kimdn** [comment]
I use 2.3.0 (singularity /share/apps/alphafold/2.3.0/alphafold).

`pip3 install jax==0.3.25 jaxlib==0.3.25+cuda11.cudnn805 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html`
solved my issue.

I updated some paths of your run_fea_gen.sh

Now I need to solve
`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-10.3.0/hmmer-3.3.2-y25u7humnxtqnaf7yc2il3misyze6pac/bin/jackhmmer'`

So you specified
`export HMMER=/usr/local/pace-apps/spack/packages/linux-rhel7-xj6_64/gcc-10.3.0/hmmer-3.3.2-y25u7humnxtqnaf7yc2il3misyze6pac
`

But I don't know where my HMMER path is.
Did you download it from somewhere?

For me, I don't need to specify hmmer path to run alphafold and alphafold-multimer.

**Comment by FreshAirTonight** [comment]
> I use 2.3.0 (singularity /share/apps/alphafold/2.3.0/alphafold).
> 
> `pip3 install jax==0.3.25 jaxlib==0.3.25+cuda11.cudnn805 -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html` solved my issue. Thank you.
> 
> I updated some paths of your run_fea_gen.sh
> 
> Now I need to solve `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/pace-apps/spack/packages/linux-rhel7-x86_64/gcc-10.3.0/hmmer-3.3.2-y25u7humnxtqnaf7yc2il3misyze6pac/bin/jackhmmer'`
> 
> So you specified `export HMMER=/usr/local/pace-apps/spack/packages/linux-rhel7-xj6_64/gcc-10.3.0/hmmer-3.3.2-y25u7humnxtqnaf7yc2il3misyze6pac `
> 
> But I don't know where my HMMER path is. Did you download it from somewhere?
> 
> For me, I don't need to specify hmmer path to run alphafold and alphafold-multimer.

The AF2 container you used has third party tools installed within. To install them independent of the container, you need to follow this [Dockerfile](https://github.com/deepmind/alphafold/blob/main/docker/Dockerfile) to install hmm, hh-suite and kalign for MSA searches.

Alternatively, when you build the container, add an additional python module `networkx`. Then, you should be able to use this  container to run both AF2Complex and AF2.

**Comment by kimdn** [comment]
I solved HMMER and other library issues by using
`export HMMER=$HOME`

My bin has jackhmmer, hmmbuild and hmmsearch

I could generate features.
