### ISSUE TITLE
Code in example1.sh, example4.sh and examples.sh appears to be incomplete

### ISSUE THREAD

**Issue by mnrusimh** [FreshAirTonight/af2complex#19]
The last line ended with a line continuation character:

`
python -u $af_dir/run_af2c_mod.py --target_lst_path=$target_lst_file \
  --data_dir=$DATA_DIR --output_dir=$out_dir --feature_dir=$fea_dir \
  --model_names=$model \
  --preset=$preset \
  --model_preset=$model_preset \
  --save_recycled=$recycling_setting \
  --msa_pairing=$msa_pairing \
`

**Comment by mnrusimh** [comment]
Same is the case with example4.sh and examples.sh (I guess it was meant to be example5.sh)

**Comment by FreshAirTonight** [comment]
This is not a bug. You may remove the last `\`. It is convenient if you would like to add additional options.
