### ISSUE TITLE
Calculating the predicted interface TM-score and the interface score.

### ISSUE THREAD

**Issue by IlyesAbdelhamid** [FreshAirTonight/af2complex#2]
Hello,

I would like to know whether it is possible to calculate both the predicted interface TM-score and the interface score from the features.pkl only ? 
I am looking for a way to extract just what it is required for the calculation of these two metrics without running the entire AF2 pipeline. 
Thank you in advance for your help. 

Sincerely,
Ilyes

**Comment by FreshAirTonight** [comment]
Ilyes,

The interface score or interface TM-score is calculated based on a predicted structure model, specifically, the result (output as a pickle) from AF2 deep learning inference. It is not possible to calculate these two scores directly on features.pkl w/o through the model inference step. However, with the features.pkl, you may run AF2Complex to predict structure models and get the scores you need, w/o going through the feature derivation step (skipping all sequence library searches). Af2Complex works with features of either individuals monomers or of a multimer feature set. Please see the examples for both cases.

**Comment by IlyesAbdelhamid** [comment]
Thank you very much for your prompt reply. I managed to include the metrics in AF v2.1.2 and compute them.
Thousand apologies for the delay!
