### ISSUE TITLE
Error finding features

### ISSUE THREAD

**Issue by cassie-sims** [FreshAirTonight/af2complex#20]
I get this error when running the run_af2comp.sh script.

 **could not locate feature input file under features/**
 
 I have made a file named 'features' within which are files with the proteins names as in the .lst file, and features generated using the run_fea_gen.sh script.
 
 My .lst file reads as follows:
 
 
##Target(components) Size(AAs) Name(for output)
PXYLORCO:2/PXYLOR1:2 1790 PXLY22

There are two folders in 'features'
PXYLOR1  PXYLORCO

within each file is a features.pkl and .fas file.

**Comment by FreshAirTonight** [comment]
The python run script looks for feature pickle files under `$fea_dir/$monomer_name`. In `run_af2comp.sh`, the default `$fea_dir` is `af2c_fea`. Try place your feature folders, `PXYLOR1` and `PXYLORCO`, under `af2c_fea` as subfolders. Or change the location of `$fea_dir` to point it to the correct path that has `PXYLOR1` and `PXYLORCO` as subfolders.

**Comment by cassie-sims** [comment]
Hi!
I realise it was because I specified the $fea_dir name in a way the python files in af2complex couldnt find it from their location. Fixed now. Thank you for a quick response :)


Cassie
