### ISSUE TITLE
AlphaFold2 Complex is not using the GPU

### ISSUE THREAD

**Issue by Drvanon** [FreshAirTonight/af2complex#4]
When I run this on my computer, the GPU is not used. There also seems to be no argument/option I can provide to force usage of the GPU. Right now I have a run time of ~7h, so any speed up would be very welcome.

**Comment by FreshAirTonight** [comment]
Please check the two closed issues that might have addressed your issue.

**Comment by Drvanon** [comment]
The issue was that I was running this in a docker container that did not have access to my gpus. Running docker with `--gpus all` did the trick.
