### ISSUE TITLE
the runtime of the procedure

### ISSUE THREAD

**Issue by Qmi3** [FreshAirTonight/af2complex#7]
when i input a pair of proteins with total length ~ 1200 and run the monomer_ptm model ,i have almost spent 4~5 hours to receive the result. Is it normal? i test this example on nvidia A100 and spent also 50mins on the test example you give.

**Comment by FreshAirTonight** [comment]
If you ran all five monomer_ptm models and each up to 20 recycles on your 1,200AA target, it is possible to take 4 to 5 hours. If it is just a single model with short recycles, then the run time seems too long for an A100.

**Comment by FreshAirTonight** [comment]
It appears that you were running one model with only three recycles on an A100 workstation. If this is case, you should get your results very quickly, less than 15 minutes, for a target with ~1000AAs. Three-hour on an A100 can model a 2700AA target for 6 recycles.

You may want to first check if the run is on the GPU. Command such as `nvidia-smi` is handy for a quick check. GPU utility during the run should be 100% or close to 100%.

**Comment by Qmi3** [comment]
Yeah, i found the GPU utility was too low and sloved this problem by downgrade the version jax & jaxlib inspired by the previous issues  Very low gpu utilization when running examples #3 . Thank you for your reply!
